/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import control.Cryptos;
import control.ShiftCipher;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.File;

/**
 *
 * @author JhhToshiba
 */
public class mainGui extends javax.swing.JFrame {

    Cryptos criptos;
    boolean ciOrde;
    DialogSubstitution dialogSubst;

    /**
     * Creates new form mainGui
     */
    public mainGui() {
        initComponents();
        TextAreaCipher.setEnabled(false);
        TextAreaClear.setEnabled(false);
        ButtonDecrypt.setEnabled(false);
        ButtonCrypt.setEnabled(false);
        dialogSubst = new DialogSubstitution(new javax.swing.JFrame(), true, true);
        dialogSubst.setVisible(false);
        cleanTextAreas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        DialogShiftKey = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        ButtonAcceptShift = new javax.swing.JButton();
        ButtonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextFieldClaveShift = new javax.swing.JFormattedTextField();
        ButtonToolsBoxShift = new javax.swing.JButton();
        DialogError = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DialogToolsShift = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextAreaAllPlains = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        PanelClearText = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaClear = new javax.swing.JTextArea();
        ButtonCrypt = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        PanelEncryptText = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaCipher = new javax.swing.JTextArea();
        ButtonDecrypt = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        PanelSelectCipher = new javax.swing.JPanel();
        ComboBoxAlgorithms = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        DialogShiftKey.setMinimumSize(new java.awt.Dimension(400, 200));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Clave"));

        ButtonAcceptShift.setText("Aceptar");
        ButtonAcceptShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAcceptShiftActionPerformed(evt);
            }
        });

        ButtonCancel.setText("Cancelar");
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresar Clave: ");

        jLabel2.setText("El valor ingresado para la clave, debe estar entre los valores");

        jLabel3.setText("[0 - 25]");

        ButtonToolsBoxShift.setText("Caja Herramientas");
        ButtonToolsBoxShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonToolsBoxShiftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonToolsBoxShift)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonAcceptShift)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldClaveShift, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(TextFieldClaveShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAcceptShift)
                    .addComponent(ButtonCancel)
                    .addComponent(ButtonToolsBoxShift))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout DialogShiftKeyLayout = new javax.swing.GroupLayout(DialogShiftKey.getContentPane());
        DialogShiftKey.getContentPane().setLayout(DialogShiftKeyLayout);
        DialogShiftKeyLayout.setHorizontalGroup(
            DialogShiftKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogShiftKeyLayout.setVerticalGroup(
            DialogShiftKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DialogError.setMinimumSize(new java.awt.Dimension(273, 93));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Error en clave");

        javax.swing.GroupLayout DialogErrorLayout = new javax.swing.GroupLayout(DialogError.getContentPane());
        DialogError.getContentPane().setLayout(DialogErrorLayout);
        DialogErrorLayout.setHorizontalGroup(
            DialogErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogErrorLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(DialogErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(98, 98, 98))
        );
        DialogErrorLayout.setVerticalGroup(
            DialogErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogErrorLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        DialogToolsShift.setMinimumSize(new java.awt.Dimension(300, 380));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Posibles Textos"));

        TextAreaAllPlains.setColumns(30);
        TextAreaAllPlains.setRows(25);
        jScrollPane3.setViewportView(TextAreaAllPlains);

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout DialogToolsShiftLayout = new javax.swing.GroupLayout(DialogToolsShift.getContentPane());
        DialogToolsShift.getContentPane().setLayout(DialogToolsShiftLayout);
        DialogToolsShiftLayout.setHorizontalGroup(
            DialogToolsShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogToolsShiftLayout.setVerticalGroup(
            DialogToolsShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelClearText.setBorder(javax.swing.BorderFactory.createTitledBorder("Texto en claro"));
        PanelClearText.setToolTipText("");
        PanelClearText.setName(""); // NOI18N

        TextAreaClear.setColumns(20);
        TextAreaClear.setRows(5);
        jScrollPane1.setViewportView(TextAreaClear);

        ButtonCrypt.setText("Cifrar");
        ButtonCrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCryptActionPerformed(evt);
            }
        });

        jButton3.setText("Nuevo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("Copiar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelClearTextLayout = new javax.swing.GroupLayout(PanelClearText);
        PanelClearText.setLayout(PanelClearTextLayout);
        PanelClearTextLayout.setHorizontalGroup(
            PanelClearTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClearTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClearTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGroup(PanelClearTextLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(ButtonCrypt, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelClearTextLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        PanelClearTextLayout.setVerticalGroup(
            PanelClearTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClearTextLayout.createSequentialGroup()
                .addGroup(PanelClearTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ButtonCrypt))
        );

        PanelEncryptText.setBorder(javax.swing.BorderFactory.createTitledBorder("Texto encriptado"));
        PanelEncryptText.setPreferredSize(new java.awt.Dimension(196, 214));

        TextAreaCipher.setColumns(20);
        TextAreaCipher.setRows(5);
        jScrollPane2.setViewportView(TextAreaCipher);

        ButtonDecrypt.setText("Descrifrar");
        ButtonDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDecryptActionPerformed(evt);
            }
        });

        jButton4.setText("Nuevo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Copiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEncryptTextLayout = new javax.swing.GroupLayout(PanelEncryptText);
        PanelEncryptText.setLayout(PanelEncryptTextLayout);
        PanelEncryptTextLayout.setHorizontalGroup(
            PanelEncryptTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEncryptTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEncryptTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addGroup(PanelEncryptTextLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(ButtonDecrypt, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEncryptTextLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        PanelEncryptTextLayout.setVerticalGroup(
            PanelEncryptTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEncryptTextLayout.createSequentialGroup()
                .addGroup(PanelEncryptTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ButtonDecrypt)
                .addGap(0, 0, 0))
        );

        PanelSelectCipher.setBorder(javax.swing.BorderFactory.createTitledBorder("Algoritmos de cifrado"));
        PanelSelectCipher.setName(""); // NOI18N

        ComboBoxAlgorithms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Desplazamiento", "Sustitucion", "Afin", "Vigenere", "Hill", "Permutacion", "DES-S", "DES", "AES" }));

        javax.swing.GroupLayout PanelSelectCipherLayout = new javax.swing.GroupLayout(PanelSelectCipher);
        PanelSelectCipher.setLayout(PanelSelectCipherLayout);
        PanelSelectCipherLayout.setHorizontalGroup(
            PanelSelectCipherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelectCipherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxAlgorithms, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSelectCipherLayout.setVerticalGroup(
            PanelSelectCipherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelectCipherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxAlgorithms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem6.setText("Cifrador Imagenes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Herramientas");

        jMenuItem2.setText("Diagrama de Frecuencias");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelClearText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelEncryptText, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(PanelSelectCipher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelClearText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelEncryptText, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSelectCipher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCryptActionPerformed
        ciOrde = true;
        dialogSubst.setCiOrDe(ciOrde);
        switch (ComboBoxAlgorithms.getSelectedIndex()) {
            case 0:
                DialogShiftKey.setVisible(true);
                ButtonToolsBoxShift.setEnabled(false);
                break;
            case 1:
                dialogSubst.setVisible(true);
                break;
            case 2:
                DiialogAffine dialogAffine = new DiialogAffine(new javax.swing.JFrame(), true, ciOrde);
                dialogAffine.setVisible(true);
                break;
            case 3:
                DialogVigenere dialogVigenere = new DialogVigenere(new javax.swing.JFrame(), true, ciOrde);
                dialogVigenere.setVisible(true);
                break;
            case 5:
                DialogPermutation dialogPermutation = new DialogPermutation(new javax.swing.JFrame(), true, ciOrde);
                dialogPermutation.setVisible(true);
                break;
            case 6:
                DialogDESS dialogDESS = new DialogDESS(new javax.swing.JFrame(), true, ciOrde);
                dialogDESS.setVisible(true);
                break;
            case 7:
                DialogDES dialogDES = new DialogDES(new javax.swing.JFrame(), true, ciOrde);
                dialogDES.setVisible(true);
                break;
            case 8:
                DialogAES dialogAES = new DialogAES(new javax.swing.JFrame(), true, ciOrde);
                dialogAES.setVisible(true);
                break;
        }
    }//GEN-LAST:event_ButtonCryptActionPerformed

    private void ButtonDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDecryptActionPerformed
        ciOrde = false;
        dialogSubst.setCiOrDe(ciOrde);
        switch (ComboBoxAlgorithms.getSelectedIndex()) {
            case 0:
                DialogShiftKey.setVisible(true);
                ButtonToolsBoxShift.setEnabled(true);
                break;
            case 1:
                dialogSubst.setVisible(true);
                break;
            case 2:
                DiialogAffine dialogAffine = new DiialogAffine(new javax.swing.JFrame(), true, ciOrde);
                dialogAffine.setVisible(true);
                break;
            case 3:
                DialogVigenere dialogVigenere = new DialogVigenere(new javax.swing.JFrame(), true, ciOrde);
                dialogVigenere.setVisible(true);
                break;
            case 5:
                DialogPermutation dialogPermutation = new DialogPermutation(new javax.swing.JFrame(), true, ciOrde);
                dialogPermutation.setVisible(true);
                break;
            case 7:
                DialogDES dialogDES = new DialogDES(new javax.swing.JFrame(), true, ciOrde);
                dialogDES.setVisible(true);
                break;
            case 8:
                DialogAES dialogAES = new DialogAES(new javax.swing.JFrame(), true, ciOrde);
                dialogAES.setVisible(true);
                break;
        }
    }//GEN-LAST:event_ButtonDecryptActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DialogError.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        DialogShiftKey.setVisible(false);
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void ButtonAcceptShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAcceptShiftActionPerformed
        int num = -1;
        try {
            num = Integer.parseInt(TextFieldClaveShift.getText());
        } catch (Exception e) {
            DialogError.setVisible(true);
        }
        if (num >= 0 && num <= 25) {
            if (ciOrde) {
                shiftAcceptCipher(true, num);
            } else {
                shiftAcceptCipher(false, num);
            }
            DialogShiftKey.setVisible(false);
        } else {
            DialogError.setVisible(true);
        }
    }//GEN-LAST:event_ButtonAcceptShiftActionPerformed
    public void shiftAcceptCipher(boolean ciph, int num) {
        int algoritmo = ComboBoxAlgorithms.getSelectedIndex();
        if (ciph) {
            criptos = new Cryptos(algoritmo, TextAreaClear.getText(), true, num);
            TextAreaCipher.setText(criptos.cSystem.cipher());
        } else {
            criptos = new Cryptos(algoritmo, TextAreaCipher.getText(), false, num);
            TextAreaClear.setText(criptos.cSystem.decipher());
        }
    }
    private void ButtonToolsBoxShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonToolsBoxShiftActionPerformed
        DialogToolsShift.setVisible(true);
        ShiftCipher _criptos = new ShiftCipher(TextAreaCipher.getText(), false, 0);
        for (int i = 0; i < 26; i++) {
            TextAreaAllPlains.setText(TextAreaAllPlains.getText() + (_criptos.posibilities())[i] + " clave " + (i) + "\n");
        }
    }//GEN-LAST:event_ButtonToolsBoxShiftActionPerformed
    public void copyClipboard(String copy) {
        StringSelection stringSelection = new StringSelection(copy);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TextAreaAllPlains.setText("");
        DialogToolsShift.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        /*File directory=new File("../../Carpeta Resultados/Imagenes"); 
         directory.mkdir(); 
         DialogImages dialogImages = new DialogImages(new javax.swing.JFrame(), true);
         dialogImages.setVisible(true);*/
        DialogImageOption dialogImageOpt = new DialogImageOption(new javax.swing.JFrame(), true);
        dialogImageOpt.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TextAreaCipher.setEnabled(false);
        TextAreaClear.setEnabled(true);
        ButtonDecrypt.setEnabled(false);
        ButtonCrypt.setEnabled(true);
        cleanTextAreas();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TextAreaCipher.setEnabled(true);
        TextAreaClear.setEnabled(false);
        ButtonDecrypt.setEnabled(true);
        ButtonCrypt.setEnabled(false);
        cleanTextAreas();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        copyClipboard(TextAreaClear.getText());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        copyClipboard(TextAreaCipher.getText());
    }//GEN-LAST:event_jButton5ActionPerformed
    private void cleanTextAreas() {
        TextAreaCipher.setText("");
        TextAreaClear.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAcceptShift;
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonCrypt;
    private javax.swing.JButton ButtonDecrypt;
    private javax.swing.JButton ButtonToolsBoxShift;
    private javax.swing.JComboBox ComboBoxAlgorithms;
    private javax.swing.JDialog DialogError;
    private javax.swing.JDialog DialogShiftKey;
    private javax.swing.JDialog DialogToolsShift;
    private javax.swing.JPanel PanelClearText;
    private javax.swing.JPanel PanelEncryptText;
    private javax.swing.JPanel PanelSelectCipher;
    private javax.swing.JTextArea TextAreaAllPlains;
    public static javax.swing.JTextArea TextAreaCipher;
    public static javax.swing.JTextArea TextAreaClear;
    private javax.swing.JFormattedTextField TextFieldClaveShift;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
